import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {render,metadata,origin,basePath,languages,pathFor,schema} from '../.prerender/render.js';
const template=await readFile('dist/index.html','utf8');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
for(const lang of languages){const data=metadata[lang];const url=origin+pathFor(lang);const head=`<link rel="canonical" href="${url}"/>\n${languages.map(l=>`<link rel="alternate" hreflang="${l}" href="${origin+pathFor(l)}"/>`).join('\n')}\n<link rel="alternate" hreflang="x-default" href="${origin}${basePath}/"/>\n<meta property="og:type" content="website"/><meta property="og:site_name" content="Shlep Auto Bartje TOLI"/><meta property="og:title" content="${escape(data.title)}"/><meta property="og:description" content="${escape(data.description)}"/><meta property="og:url" content="${url}"/><meta property="og:locale" content="${data.locale}"/><meta property="og:image" content="${origin}${basePath}/images/corvette.jpg"/><meta name="twitter:card" content="summary_large_image"/><script type="application/ld+json">${JSON.stringify(schema(lang)).replaceAll('<','\\u003c')}</script>`;
let html=template.replace('<html lang="sq">',`<html lang="${lang}">`).replace(/<title>.*?<\/title>/,`<title>${escape(data.title)}</title>`).replace(/<meta name="description" content="[^"]*"\s*\/>/,`<meta name="description" content="${escape(data.description)}"/>`).replace('</head>',head+'</head>').replace('<div id="root"></div>',`<div id="root">${await render(lang)}</div>`);
const folder=lang==='sq'?'dist':`dist/${lang}`;await mkdir(folder,{recursive:true});await writeFile(`${folder}/index.html`,html);console.log(`Pre-rendered ${pathFor(lang)} in ${lang}`);
}
await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}${basePath}/sitemap.xml\n`);
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${languages.map(lang=>`<url><loc>${origin+pathFor(lang)}</loc>${languages.map(l=>`<xhtml:link rel="alternate" hreflang="${l}" href="${origin+pathFor(l)}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${origin}${basePath}/"/></url>`).join('')}</urlset>`);
await writeFile('dist/404.html','<!doctype html><html lang="sq"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Faqja nuk u gjet | TOLI</title><meta name="robots" content="noindex"><body style="font-family:system-ui;padding:10vw;background:#f8f8f3;color:#20231f"><h1>Faqja nuk u gjet / Page not found</h1><a href="/shlep-toli/">TOLI — Kthehu në kryefaqe / Back to home</a></body></html>');
