import { pathFor } from './seo';
export const privacyPath = (language: string) => `${pathFor(language)}privacy/`;
export const privacyText = {
  sq: {
    title: 'Politika e privatësisë', back: 'Kthehu në kryefaqe', settings: 'Cookies dhe privatësia', okay: 'Në rregull', updated: 'Përditësuar më 4 tetor 2026',
    notice: 'Nuk përdorim cookies për reklama ose analiza. Ruajmë vetëm zgjedhjen tuaj për këtë njoftim në këtë pajisje. Shërbimet e jashtme kanë politikat e tyre të privatësisë.',
    intro: 'Si i trajton Shlep Auto Bartje TOLI të dhënat kur vizitoni këtë faqe ose na kontaktoni.',
    sections: [
      ['Kush jemi dhe si të na kontaktoni', 'Shlep Auto Bartje TOLI, Bellanicë, Malishevë 24000, Kosovë. Për pyetje rreth privatësisë ose të dhënave që na keni dërguar, telefononi ose na shkruani në WhatsApp në +383 44 116 446.'],
      ['Formulari i kontaktit dhe WhatsApp', 'Emri, telefoni, shërbimi, lokacioni i nisjes, destinacioni dhe shënimet përpunohen në shfletuesin tuaj për të përgatitur kërkesën. Formulari nuk i dërgon në një server të TOLI-t dhe nuk i ruan në bazë të dhënash. Kur klikoni “Vazhdo në WhatsApp”, teksti i kërkesës i kalon WhatsApp-it përmes një lidhjeje. TOLI e merr mesazhin vetëm pasi ju shtypni Dërgo në WhatsApp. Lidhja mund të mbetet në historikun e shfletuesit; mos përfshini të dhëna të panevojshme ose të ndjeshme.'],
      ['Pse përdorim të dhënat që na dërgoni', 'Të dhënat në mesazhet dhe telefonatat tuaja përdoren për t’ju përgjigjur, për të përgatitur ofertën dhe për të organizuar asistencën ose transportin që kërkoni. Jepni vetëm informacionin e nevojshëm për kërkesën tuaj. Për ruajtjen ose fshirjen e një bisede apo dokumenti të shërbimit, na kontaktoni në numrin e mësipërm; disa dokumente mund të duhet të ruhen sipas detyrimeve ligjore.'],
      ['Cookies dhe ruajtja në pajisje', 'Faqja nuk instalon cookies për reklama apo analiza dhe nuk përfshin mjete gjurmimi. Pasi mbyllni njoftimin, localStorage ruan vetëm toli-privacy-notice-v1 me vlerën acknowledged. Kjo e mban njoftimin të mbyllur në këtë shfletues; nuk ruan të dhënat e formularit dhe nuk dërgohet te TOLI. Mund ta rihapni nga lidhja “Cookies dhe privatësia” në fund të faqes ose ta fshini përmes cilësimeve të shfletuesit. Nëse ruajtja bllokohet, faqja funksionon dhe njoftimi mund të shfaqet përsëri.'],
      ['Hostimi dhe shërbimet e jashtme', 'Faqja hostohet në GitHub Pages. GitHub mund të përpunojë informacion teknik, përfshirë adresën IP dhe të dhënat e kërkesës, për ofrimin dhe sigurinë e shërbimit. Fotot dhe fontet shërbehen nga kjo faqe. Google Maps, Facebook, TikTok dhe WhatsApp hapen vetëm kur klikoni lidhjet përkatëse. Këto shërbime zbatojnë politikat e tyre dhe mund të përpunojnë të dhëna jashtë Kosovës.'],
      ['Kërkesat tuaja dhe ndryshimet', 'Mund të na kontaktoni për qasje, korrigjim ose fshirje të të dhënave që na keni dërguar, sipas të drejtave që zbatohen për ju. Mund të kërkojmë informacion për të verifikuar identitetin tuaj para përgjigjes. Kjo politikë përshkruan funksionimin aktual të faqes; ndryshimet do të publikohen këtu me datën e përditësimit.']
    ], links: 'Politikat e shërbimeve të jashtme'
  },
  en: {
    title: 'Privacy policy', back: 'Back to home', settings: 'Cookies & privacy', okay: 'Got it', updated: 'Updated 4 October 2026',
    notice: 'We use no advertising or analytics cookies. We save only your choice about this notice on this device. External services have their own privacy policies.',
    intro: 'How Shlep Auto Bartje TOLI handles information when you visit this website or contact us.',
    sections: [
      ['Who we are and how to contact us', 'Shlep Auto Bartje TOLI, Bellanicë, Malishevë 24000, Kosovo. For privacy questions or requests about information you have sent us, call or message us on WhatsApp at +383 44 116 446.'],
      ['Contact form and WhatsApp', 'Your name, phone number, service, pickup location, destination and notes are processed in your browser to prepare your request. The form does not send them to a TOLI server or store them in a database. Clicking “Continue in WhatsApp” passes the request text to WhatsApp through a link. TOLI receives the message only after you press Send in WhatsApp. The link may remain in your browser history; do not include unnecessary or sensitive information.'],
      ['Why we use information you send us', 'Information in your messages and calls is used to reply, prepare a quote and arrange the assistance or transport you request. Please provide only information needed for your request. For retention or deletion of a conversation or service record, contact the number above; some records may need to be retained to meet legal obligations.'],
      ['Cookies and device storage', 'This website does not install advertising or analytics cookies and includes no tracking tools. After you dismiss the notice, localStorage saves only toli-privacy-notice-v1 with the value acknowledged. This keeps the notice dismissed in this browser; it does not store form details and is not sent to TOLI. Reopen it using “Cookies & privacy” in the footer or remove the saved value through your browser settings. If storage is blocked, the website still works and the notice may appear again.'],
      ['Hosting and external services', 'This website is hosted on GitHub Pages. GitHub may process technical information, including your IP address and request data, to provide and secure its service. Photos and fonts are served by this website. Google Maps, Facebook, TikTok and WhatsApp open only when you follow their links. These services apply their own policies and may process data outside Kosovo.'],
      ['Your requests and policy changes', 'Contact us to request access to, correction or deletion of information you have sent us, subject to the rights applicable to you. We may need information to verify your identity before responding. This policy describes the website’s current operation; changes will be published here with an updated date.']
    ], links: 'External service privacy policies'
  },
  de: {
    title: 'Datenschutzerklärung', back: 'Zurück zur Startseite', settings: 'Cookies & Datenschutz', okay: 'Verstanden', updated: 'Aktualisiert am 4. Oktober 2026',
    notice: 'Wir verwenden keine Werbe- oder Analyse-Cookies. Auf diesem Gerät speichern wir nur Ihre Auswahl zu diesem Hinweis. Externe Dienste haben eigene Datenschutzrichtlinien.',
    intro: 'Wie Shlep Auto Bartje TOLI Informationen verarbeitet, wenn Sie diese Website besuchen oder uns kontaktieren.',
    sections: [
      ['Wer wir sind und wie Sie uns erreichen', 'Shlep Auto Bartje TOLI, Bellanicë, Malishevë 24000, Kosovo. Bei Datenschutzfragen oder Anfragen zu übermittelten Daten erreichen Sie uns telefonisch oder über WhatsApp unter +383 44 116 446.'],
      ['Kontaktformular und WhatsApp', 'Name, Telefonnummer, gewünschter Service, Abholort, Ziel und Hinweise werden in Ihrem Browser verarbeitet, um Ihre Anfrage vorzubereiten. Das Formular sendet diese Daten nicht an einen TOLI-Server und speichert sie nicht in einer Datenbank. Mit „Weiter in WhatsApp“ wird der Text über einen Link an WhatsApp übergeben. TOLI erhält die Nachricht erst, wenn Sie in WhatsApp auf Senden klicken. Der Link kann im Browserverlauf bleiben; geben Sie keine unnötigen oder sensiblen Daten an.'],
      ['Wofür wir übermittelte Informationen verwenden', 'Angaben aus Ihren Nachrichten und Anrufen dienen dazu, zu antworten, ein Angebot vorzubereiten und die gewünschte Hilfe oder den Transport zu organisieren. Geben Sie bitte nur die dafür notwendigen Informationen an. Zur Aufbewahrung oder Löschung einer Unterhaltung oder eines Servicebelegs kontaktieren Sie uns unter der obigen Nummer; gesetzliche Pflichten können die Aufbewahrung bestimmter Unterlagen erfordern.'],
      ['Cookies und Speicherung auf Ihrem Gerät', 'Diese Website setzt keine Werbe- oder Analyse-Cookies und enthält keine Tracking-Tools. Nach dem Schließen des Hinweises speichert localStorage nur toli-privacy-notice-v1 mit dem Wert acknowledged. Dadurch bleibt der Hinweis in diesem Browser geschlossen. Formulardaten werden dort nicht gespeichert; der Wert wird nicht an TOLI gesendet. Über „Cookies & Datenschutz“ im Seitenfuß können Sie den Hinweis erneut öffnen oder den gespeicherten Wert in Ihren Browsereinstellungen löschen. Bei blockiertem Speicher funktioniert die Website weiterhin; der Hinweis kann erneut erscheinen.'],
      ['Hosting und externe Dienste', 'Diese Website wird auf GitHub Pages gehostet. GitHub kann technische Daten wie IP-Adresse und Anfragedaten verarbeiten, um seinen Dienst bereitzustellen und abzusichern. Fotos und Schriftarten werden von dieser Website geladen. Google Maps, Facebook, TikTok und WhatsApp öffnen sich nur, wenn Sie den jeweiligen Links folgen. Für diese Dienste gelten eigene Richtlinien; Daten können außerhalb des Kosovo verarbeitet werden.'],
      ['Ihre Anfragen und Änderungen', 'Sie können uns bezüglich Auskunft, Berichtigung oder Löschung Ihrer übermittelten Daten im Rahmen Ihrer geltenden Rechte kontaktieren. Vor einer Antwort können wir Informationen zur Identitätsprüfung benötigen. Diese Erklärung beschreibt die aktuelle Funktionsweise der Website. Änderungen werden hier mit aktualisiertem Datum veröffentlicht.']
    ], links: 'Datenschutzrichtlinien externer Dienste'
  }
};
export function privacyCopy(language: string) { return privacyText[language as keyof typeof privacyText] || privacyText.sq; }
